version: "3.9"
services:
  tutor:
    build: .
    container_name: ai-tutor-sketchpad
    environment:
      # Optional: pass an API key if you wire a real LLM
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped
